[package]
name = "signer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ecdsa.workspace = true
serde.workspace = true
serde_json.workspace = true