[package]
name = "avs-node-metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true