[package]
name = "tracing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
tracing-subscriber.workspace = true
tracing.workspace = true